### PR TITLE
Add contact info to FAQs page

### LINKED ISSUE #11: Add feedback disclaimer
Add some sort of text that says "please send comments and feedback to swantonpoppycp@gmail.com?" or something along those lines.

### PR DESCRIPTION
**Pull request by Jason-Ku**
Closes #11 

### Notes
* Add contact info message on FAQs page

### Testing
Local compile
image

### CODE REVIEW

**Comment by Jason-Ku** [comment]
Don't know how to best get the text to be at the bottom of the div, any suggestions?

**Comment by Waidhoferj** [comment]
@Jason-Ku Thoughts on this fix? The message will stay on the bottom and won't overlap when elements begin to scroll. I used a flexbox to get this behavior.

**Comment by Jason-Ku** [comment]
That sounds great, John! I'll have to look into flexboxes after this to see what else they can be used for ^^

**Review by Waidhoferj — APPROVED** [review]
Sorry forgot to approve. The change looks good, but I'm a little biased, so maybe get one other person too

**Comment by Jason-Ku** [comment]
Just talked to miles offline and he gave it the green light, will merge

**Review by snekiam — APPROVED** [review]
I'm one other person! Looks good to me.

**Pull request merged**
